---
# https://github.com/ansible/ansible/pull/46159
- name: Install xz-utils
  become: true
  apt:
    name: xz-utils
    update_cache: true

- name: Install fetch
  become: true
  tags: fetch
  get_url:
    url: https://github.com/gruntwork-io/fetch/releases/download/v0.4.1/fetch_linux_amd64
    dest: /usr/local/bin/fetch
    mode: 0755
    force: true

- name: Fetch deb
  shell: >-
    fetch --repo
    https://github.com/dshearer/jobber
    --release-asset=".*amd64.deb"
    --tag=v1.4.4 /tmp

- name: Install deb
  become: true
  apt:
    deb: /tmp/jobber_1.4.4-1_amd64.deb

- name: Enable systemd service
  become: true
  systemd:
    name: jobber.service
    state: started
    enabled: true

- name: Setup jobber configs
  notify: reload_jobber
  become: true
  copy:
    content: '{{ item.value | to_yaml }}'
    dest: '{{ "/root/.jobber" if item.key == "root" else "/home/"+item.key+"/.jobber" }}'
    mode: 0644
    owner: '{{ item.key }}'
    group: '{{ item.key }}'
  loop: '{{ jobber_configs | dict2items }}'
