---
# https://github.com/ansible/ansible/pull/46159
- name: Install xz-utils
  apt:
    name: xz-utils
    update_cache: true

- name: Get latest release
  uri:
    url: https://api.github.com/repos/dshearer/jobber/releases/latest
    timeout: 5
  register: jobber_latest_release
  changed_when: false

- name: Get download url
  set_fact:
    # Why to_json | from_json?
    # https://github.com/ansible/ansible/issues/27299
    jobber_deb_download_url: >-
      {{ jobber_latest_release.json.assets |
         to_json | from_json |
         json_query("[?contains(name, 'amd64.deb')].browser_download_url | [0]") |
         trim
      }}

- name: Install deb
  become: true
  apt:
    deb: '{{ jobber_deb_download_url }}'

- name: Enable systemd service
  systemd:
    name: jobber.service
    state: started
    enabled: true

- name: Setup jobber configs
  notify: reload_jobber
  copy:
    content: '{{ item.value | to_yaml }}'
    dest: '{{ "/root/.jobber" if item.key == "root" else "/home/"+item.key+"/.jobber" }}'
    mode: 0644
    owner: '{{ item.key }}'
    group: '{{ item.key }}'
  loop: '{{ jobber_configs | dict2items }}'
